# Generated by Django 6.1.1 on 2026-09-16 05:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wholesaler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=120)),
                ('name', models.CharField(blank=True, help_text='Contact person.', max_length=120)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(help_text='Type any category you use.', max_length=80)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('unit', models.CharField(help_text='Every rate for this product is recorded per this unit.', max_length=16)),
                ('pack_size', models.CharField(blank=True, max_length=60)),
                ('minimum_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='manager_pro_categor_619a5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(default='My Kirana Store', max_length=120)),
                ('shop_address', models.TextField(blank=True)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('currency_symbol', models.CharField(default='₹', max_length=4)),
                ('default_unit', models.CharField(default='kg', max_length=16)),
                ('date_format', models.CharField(choices=[('dd-MM-yyyy', '31-12-2026'), ('yyyy-MM-dd', '2026-12-31'), ('dd/MM/yyyy', '31/12/2026')], default='dd-MM-yyyy', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'shop settings',
                'verbose_name_plural': 'shop settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton_id', 1)), name='shop_settings_single_row')],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit', models.CharField(max_length=16)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('other_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('effective_rate', models.DecimalField(decimal_places=2, editable=False, help_text='purchase_rate + (transport_cost + other_cost) / quantity', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='manager.product')),
                ('wholesaler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='manager.wholesaler')),
            ],
            options={
                'ordering': ['-date', '-created_at', '-id'],
                'indexes': [models.Index(fields=['product', '-date'], name='rates_product_date_idx'), models.Index(fields=['wholesaler', '-date'], name='rates_whl_date_idx'), models.Index(fields=['date'], name='rates_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, help_text='quantity * rate', max_digits=14)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('other_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('final_amount', models.DecimalField(decimal_places=2, editable=False, help_text='total_amount + transport_cost + other_cost', max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='manager.product')),
                ('wholesaler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='manager.wholesaler')),
            ],
            options={
                'ordering': ['-date', '-created_at', '-id'],
                'indexes': [models.Index(fields=['-date'], name='purchases_date_idx'), models.Index(fields=['product', '-date'], name='purchases_prod_date_idx')],
            },
        ),
    ]
